### ISSUE TITLE
Play/Pause, Prev, Next buttons all disabled on iOS11 - but seek works...

### ISSUE THREAD

**Issue by Wade-McDaniel** [homerours/cordova-music-controls-plugin#89]
Greetings,

I know there are issues with cordova-plugin-background-mode and cordova-music-controls-plugin, but I cannot seem to get the Prev, Play/Pause, or Next buttons to not be disabled on iOS11. The seek bar on the lock screen works for me, but the other buttons are just that diabled-grey color and tapping on them don't work.

I tried removing cordova-plugin-background-mode but of course hitting the power button them stops the audio so there are no lock-screen controls in that case.

Might you have any suggestions I could try?

If you suspect this is caused by background-mode, I thought about removing the background-mode plugin via Ionic but trying to enable "Background Modes > Audio, Airplay, Picture in Picture" in XCode (and then figuring out background-mode for Android somehow...), but I don't know that background-mode is the problem here because of the functioning seek bar.

I know that I am calling MusicControls.updateIsPlaying(true) because if I don't do that the seek bar doesn't move. And hasNext is true when I call MusicControls.create.

Any suggestions for me?

Thank you!

**Comment by axalon** [comment]
Having the same issue, what it looks like for me:

![img_3567](https://user-images.githubusercontent.com/16852/31911425-98892fa4-b80e-11e7-8e8c-b8fe88919f04.jpg)

**Comment by Wade-McDaniel** [comment]
Ya, I get what axalon posted a screenshot of, but the seek bar works for me and has times on either end. 

Thanks, axalon!

**Comment by Wade-McDaniel** [comment]
Oh, and I'm using version 2.0.0 of cordova-plugin-music-controls. I tried installing 2.1.1 via github, but not only did that not fix the play/pause, prev, and next buttons, but audio playback stopped working as well. So i reverted to just 2.0.0.

**Comment by Wade-McDaniel** [comment]
axalon, I discovered something here. Maybe it'll help you.

When I edited MusicControls.m to comment out two sections, the two 'if' sections that start with 'if (floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_9_0) {', that disabled seek dragging, but the play/pause, prev, next buttons showed up!

Still buggy tho: play/pause may work but prev/next don't.

I'm super-unfamilar with Objective-C and iOS, so I am stuck now. But maybe you can use what I discovered to uncover more details...

**Comment by fdambrosio** [comment]
I had the same problem. I have to use 1.4.1 version. 2.x/2.1.1 too are not working, play/pause event are not fired. 
Using 1.4.1 you have to try this code: 

```
this.myControls.subscribe().subscribe((action) => {
                    switch(action) {
....
```
and it works. (but prev/next are always showed)

similar: https://github.com/homerours/cordova-music-controls-plugin/issues/62 

example Repo https://github.com/fdambrosio/ionic-media-controls

**Comment by Wade-McDaniel** [comment]
Thanks fdambrosio!

But I tried reverting to 1.4.1 of the cordova-plugin-music-controls plugin and none of the buttons work now.

I see that your github repo you linked too doesn't use cordova-plugin-background-mode. How are you able to play audio when the device is locked without that?

**Comment by fdambrosio** [comment]
thanks @Wade-McDaniel you need to turn on the option 'background audio' on XCode: https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/ConfiguringAudioSettings/ConfiguringAudioSettings.html and the app will be able to play audio in background. 
Is it working my github repo branch 'downgrade' ?

**Comment by carlosstrand** [comment]
@Wade-McDaniel I solved with these steps:

Inside `MusicControls.m`:

```
- (void) handleMusicControlsNotification: (NSNotification *) notification {

...

    switch (receivedEvent.subtype) {
        ...
        default:
            action = nil;
            break;
    }

    if (action == nil) {
        return;
     }
    ....
}
```

More info at: https://github.com/homerours/cordova-music-controls-plugin/issues/90#issuecomment-340882887

**Comment by Wade-McDaniel** [comment]
Thanks carlosstrand!
Unfortunately that doesn't seem to solve the problem here.

I get play/pause to work if I comment out the 'if' statements in MusicControls.m that start with
if (floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_9_0) { but next/prev works once...sometimes, and then the event subType is end seek. So somewhere along the lines that event is getting hijacked and converted from UIEventSubtypeRemoteControlNextTrack to UIEventSubtypeRemoteControlEndSeekingBackward.

I'm not sure how I can figure out why the event type is correct but subtype is incorrect...that seems like an OS bug...but that's how far I've gotten on this.

**Comment by BuddyLReno** [comment]
Is anyone using the new WKWebview from Ionic? I've been able to verify on my personal fork of this repo that WKWebview breaks functionality.

**Comment by Wade-McDaniel** [comment]
Hi BuddyLReno, I'm using WKWebView from ionic, via cordova-plugin-ionic-webview. 

There are iOS 11 issues for sure with MusicControls (hence why I opened this issue), but they seem unrelated to Ionic's cordova-plugin-ionic-webview.

**Comment by BuddyLReno** [comment]
@Wade-McDaniel That's very interesting... When I have that plugin, the controls work just fine from my fork. When I add the ionic-webview plugin, they break. :/ Investigating.

**Comment by Wade-McDaniel** [comment]
Try adding `<preference name="AudioCanMix" value="true" />` to your config.xml - I read somethign sopmewhere where the WKWebView has it's own instance/thread, so AudioCanMix makes it so the WKWebView doersn't take over the main thread.

My issues with MusicControls look to be are iOS11-related, after disabling some if-statements: https://github.com/Wade-McDaniel/cordova-music-controls-plugin/commit/4a535d3da6b0b29fbe71153dbfe85fbed411f6b9#diff-5296da05d8cc4d394198df675b132d2c

So I see all of the buttons now, but something is hijacking the events changing prev/next subTypes to end-seek subTypes. Play/pause seem to work tho in some testing.

**Comment by sebaferreras** [comment]
Just to add some more information, [here](https://ionicframework.com/docs/wkwebview/#configuring-avaudiosession-doesnt-affect-wkwebview) you can find what @Wade-McDaniel mentioned related to `AudioCanMix` :

> Configuring AVAudioSession doesn’t affect WKWebView
> 
> WKWebView runs in a separate process from your app. It is likely that it has its own AudioSession separate from your app’s AudioSession. One possible workaround is to allow your app’s AudioSession to mix with others:
> 
> ```
> [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord 
>                                  withOptions:AVAudioSessionCategoryOptionMixWithOthers
>                                        error:&error];
> ```
> 
> Fortunately, Ionic’s WebView can do this for you by setting the `AudioCanMix` Cordova preference to `true`.
> 
> `<preference name="AudioCanMix" value="true" />`

**Comment by BuddyLReno** [comment]
@Wade-McDaniel @carlosstrand Can you guys try out PR #95 and let me know if that is better for you guys? I've gotten positive results with those changes.

**Comment by Wade-McDaniel** [comment]
Sure thing, @BuddyLReno - but unfortunately I'm a bit of a github n00b. Is there a URL you can point me at that described how to merge in a particular commit into my fork of music-controls?

**Comment by BuddyLReno** [comment]
@Wade-McDaniel Sure thing!

- [Configure an upstream for a fork](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
- [Sync a fork](https://help.github.com/articles/syncing-a-fork/)

**Comment by Wade-McDaniel** [comment]
Thank you! I think I managed to mess it up a bit tho, and may have pushed my changes up to the master head instead of to my fork...hopefully people can just ignore that.

In some brief testing tho it looks like all the controls are working, including seek!

@BuddyLReno I left the version check in there and just put your commandCenter stuff within there. I saw @0505gonzalez ask about that, and it looks like your changs play nice within the the version check. Thank you!

**Comment by BuddyLReno** [comment]
@Wade-McDaniel it looks like you pushed to the master of your fork. Since you're not a collaborator on this repo, you won't be able to push to master without a PR. 👍  :)

**Comment by BuddyLReno** [comment]
@Wade-McDaniel do you happen to experience any lag or have to push buttons multiple times when you use it from the lockscreen? I'm experiencing that in my app.

**Comment by Wade-McDaniel** [comment]
@BuddyLReno Nope, no lag on button push for me. But we've had people report that the cordova-plugin-media plugin isn't starting up streams very fast, but for me here on WiFi it's pretty fast.

I do need to change code so pause actually pauses and not stops, but that's a bug in my code and not MusicControls.m, so I'm pretty happy so far. But I've really only done very little testing this morning. I'll report more after my deluge of morning calls. :)

**Comment by BuddyLReno** [comment]
@Wade-McDaniel ok very interesting. I'm having to push the lockscreen controls multiple times to get them to respond. When the device is unlocked I can use the control center just fine. This only happens when I use Ionic WKWebview (as opposed to their UIWebview) so it definitely seems to be an issue with either my app or Ionic's WKWebview. :) I'm glad these issues are getting fixed for you! I actually have a fork of the Media plugin that resolves that slow start up.  It's just not configurable. If you want, check out my fork of it and you can see what I did to it.

**Comment by Wade-McDaniel** [comment]
@BuddyLReno Are you using <preference name="AudioCanMix" value="true" /> in your config.xml? Check out @sebaferreras comment from earlier in this thread: his explanation is a good one.

But if you already have that in your config.xml, then I'm stumped on your lag issue...sorry.

**Comment by Wade-McDaniel** [comment]
`<preference name="AudioCanMix" value="true" />` got parsed out in my comment

**Comment by BuddyLReno** [comment]
@Wade-McDaniel I missed that in all my back and forth. Trying that out now.

**Comment by BuddyLReno** [comment]
That didn't help but it looks like there may be other avenues to pursue. Pretty sure we don't need to do any updates here.

**Comment by Wade-McDaniel** [comment]
@BuddyLReno Quick question: If you hit pause does the seek bar jump back to 0 for you? It does for me. But if I hit play again the audio is still at the correct spot, just seek is off.

**Comment by BuddyLReno** [comment]
No, I actually get no response unless I tap multiple times.

**Comment by BuddyLReno** [comment]
Well the play button will change to pause and back and forth but nothing happens.

**Comment by Wade-McDaniel** [comment]
Just in case, have you tried deleting your platforms and plugins directories after adding in that AudioCanMix preference? I had to `rm -rf plugins && rm -rf platforms && cordova prepare` to fully test that one. Actually, I do that a lot...

**Comment by BuddyLReno** [comment]
I've done that a few times but not since adding audiocanmix. I'll try that now.

**Comment by Wade-McDaniel** [comment]
@BuddyLReno Nice! I'm still working on that seek issue. I've traced it to updateIsPlaying - trying to get teh updatedNowPlayingInfo dictionary to not set the MPNowPlayingInfoPropertyElapsedPlaybackTime value to 0, but like github, I'm not familiar with debugging in XCode, so it's slow going...

**Comment by BuddyLReno** [comment]
@Wade-McDaniel so after some more testing, the only way I got it to work was by using @ghenry22's plugin: https://github.com/ghenry22/cordova-plugin-background-mode

I don't even have to do anything, I just have to have the cordova plugin itself.

@ghenry22, can you elaborate on why that would be the case? By default the background-mode plugin is disabled. Is there some other property that is added that makes it work when the plugin is added, even if I don't do anything to activate it?

**Comment by Wade-McDaniel** [comment]
@BuddyLReno  I solved my seek-bar issue...mostly...by using updateElapsed on iOS and using {isPlaying: false, elapsed: [currentTrackPosition]} for pause button clicks instead of updateIsPlaying(false). It's not perfect as the seek bar can jump a bit, but it's better than it was. Just FYI in case it helps you (or anyone else).

Debugging why updateIsPlaying(false) moves the seek bar is currently beyond my capabilities as it turns out...

**Comment by BuddyLReno** [comment]
@Wade-McDaniel It may help that PR #96 fixed that I believe. Gavin made it so that updateElapsed forwards to isPlaying and both accept the elapsed time and set it properly now.

**Comment by fdambrosio** [comment]
thanks @BuddyLReno   PR #96 works for me! 

example repo: https://github.com/fdambrosio/ionic-media-controls/tree/merge96

**Comment by BuddyLReno** [comment]
@fdambrosio awesome! Thanks for testing!

@Wade-McDaniel did the new version of music controls (2.1.3) help?

**Comment by Wade-McDaniel** [comment]
@BuddyLReno Actually, I was under a bit of a time crunch, so I just let our testers look at the app yesterday still using my fork of music-controls: https://github.com/Wade-McDaniel/cordova-music-controls-plugin I think it has your stuff in it. They seemed happy with it on iPhone iOS11, but I haven't heard back about any iPad testing or any other OS version than 11. I plan to switch to the main music-controls branch in a few days tho, and when I do I'll use 2.1.3 - I'm sure it'll work :)

**Comment by BuddyLReno** [comment]
@Wade-McDaniel great! I'll close this issue for the time being. Thanks for all the help!

**Comment by sebaferreras** [comment]
> I solved my seek-bar issue...mostly...by using updateElapsed on iOS and using {isPlaying: false, elapsed: [currentTrackPosition]} for pause button clicks instead of updateIsPlaying(false). It's not perfect as the seek bar can jump a bit, but it's better than it was. Just FYI in case it helps you (or anyone else).

@Wade-McDaniel  I'm also having this issue with the seek-bar on iOS 11 with the WKWebView plugin, even after installing the background mode Cordova plugin.

So using `updateElapsed({ elapsed: positionInSeconds, isPlaying: false });` jumps a bit but for some reason `updateIsPlaying(false)` moves the seek bar to the start...
